const ksConfig = new Object();

ksConfig.SelectTitle = 'WYBIERZ POSTAĆ';
ksConfig.SelectSubTitle = 'Wybierz postać na której dołączysz do gry';
ksConfig.CreateTitle = 'STWÓRZ POSTAĆ';
ksConfig.CreateSubTitle = 'Stwórz swoją postać aby rozpocząć rozgrywke';

ksConfig.Male = 'MĘŻCZYZNA';
ksConfig.Female = 'KOBIETA';
ksConfig.MoneySymbole = '$'
ksConfig.NoGrade = 'BEZROBOTNY';
ksConfig.Txtbirthdate = 'Data urodzenia';
ksConfig.Txtgender = 'Płeć';
ksConfig.Txtgrade = 'Funkcja';
ksConfig.Txtcash = 'Pieniądze';
ksConfig.Txtbank = 'Banku';
ksConfig.Txtnationality = 'Narodowość'
ksConfig.Txtheight = 'Wysokość';
ksConfig.TxtheightSym = 'CM';
ksConfig.Txtdetails = 'Kliknij aby uzyskać więcej informacji';
ksConfig.EmptySlot = 'WOLNA POSTAĆ';
ksConfig.EmptySlotTxt = 'Kliknij aby stworzyć nową postać';
ksConfig.DiscordSlot = 'PREMIUM POSTAĆ';
ksConfig.DiscordSlotTxt = 'Dostęp zakup na dc.heavenproject.eu';

ksConfig.DateSymbole = '-'; // (dd-mm-yyyy) you can change it to / (dd/mm/yyyy) or anything else you want.
ksConfig.DateFormat = 'dd%mm%yyyy'; // Choices: 'dd%mm%yyyy' or 'mm%dd%yyyy' or 'yyyy%dd%mm' or 'yyyy%mm%dd'
ksConfig.MaxNameLength = 10;
ksConfig.MinNameLength = 2;
ksConfig.MinHeight = '150';
ksConfig.MaxHeight = '210';
ksConfig.LowestYear = '1920';
ksConfig.HighestYear = '2004';

ksConfig.Notfi1 = 'Wszystkie pola muszą być wypełnione!';
ksConfig.Notfi2 = 'Niepoprawnie wpisane imię bądź nazwisko! Spróbuj ponownie.';
ksConfig.Notfi3 = 'Niepoprawnie wpisana data urodzenia! Spróbuj ponownie.';
ksConfig.Notfi4 = 'Niepoprawnie wpisana wysokość postaci! Spróbuj ponownie.';
ksConfig.Notfi5 = 'Kliknij jeszcze raz aby usunąć postać!';
ksConfig.Notfi6 = 'Imie i nazwisko muszą rozpoczynać się z dużej litery!';

ksConfig.CIdenTitle = 'DANE POSTACI';
ksConfig.CIdenSubTitle = 'Nazwij swoją nową postać!';
ksConfig.CIdenFname = 'IMIĘ';
ksConfig.CIdenFnamePH = 'Jack';
ksConfig.CIdenLname = 'NAZWISKO';
ksConfig.CIdenLnamePH = 'Harris';
ksConfig.CIdenNation = 'NARODOWOŚĆ';
ksConfig.CIdenNationPH = 'USA';
ksConfig.CIdenHeight = 'WZROST';
ksConfig.CIdenHeightPH = '185';
ksConfig.CGenTitle = 'PŁEĆ';
ksConfig.CGenSubTitle = 'Wybierz płeć swojej postaci!';
ksConfig.CGenSelected = 'Wybarna:';
ksConfig.CBDTitle = 'DATA URODZENIA';
ksConfig.CBDSubTitle = 'Wpisz date urodzenia swojej postaci!';
ksConfig.CBDday = 'DZIEŃ';
ksConfig.CBDdayPH = '25';
ksConfig.CBDmonth = 'MIESIĄC';
ksConfig.CBDmonthPH = '10';
ksConfig.CBDyear = 'ROK';
ksConfig.CBDyearPH = '1958';
ksConfig.CancelBtn = 'Anuluj';
ksConfig.CreateBtn = 'Stwórz postać!';